# Markdownlint configuration
# See: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style (consistent)
MD003:
  style: "atx"

# MD004 - Unordered list style (consistent)
MD004:
  style: "dash"

# MD005 - Inconsistent indentation for list items at the same level
MD005: true

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces
MD009:
  br_spaces: 2

# MD010 - Hard tabs
MD010: true

# MD011 - Reversed link syntax
MD011: true

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length
MD013:
  line_length: 120
  headings: false
  code_blocks: false
  tables: false

# MD014 - Dollar signs used before commands without showing output
MD014: false

# MD018 - No space after hash on atx style heading
MD018: true

# MD019 - Multiple spaces after hash on atx style heading
MD019: true

# MD020 - No space inside hashes on closed atx style heading
MD020: true

# MD021 - Multiple spaces inside hashes on closed atx style heading
MD021: true

# MD022 - Headings should be surrounded by blank lines
MD022: true

# MD023 - Headings must start at the beginning of the line
MD023: true

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD025 - Multiple top level headings in the same document
MD025: true

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!?"

# MD027 - Multiple spaces after blockquote symbol
MD027: true

# MD028 - Blank line inside blockquote
MD028: true

# MD029 - Ordered list item prefix
MD029:
  style: "ordered"

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML
MD033: false  # Allow HTML (for badges, etc.)

# MD034 - Bare URL used
MD034: false

# MD035 - Horizontal rule style
MD035:
  style: "---"

# MD036 - Emphasis used instead of a heading
MD036: true

# MD037 - Spaces inside emphasis markers
MD037: true

# MD038 - Spaces inside code span elements
MD038: true

# MD039 - Spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
MD040: true

# MD041 - First line in file should be a top level heading
MD041: false

# MD042 - No empty links
MD042: true

# MD043 - Required heading structure
MD043: false

# MD044 - Proper names should have the correct capitalization
MD044: false

# MD045 - Images should have alternate text (alt text)
MD045: true

# MD046 - Code block style
MD046:
  style: "fenced"

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style
MD048:
  style: "backtick"

# MD049 - Emphasis style should be consistent
MD049:
  style: "asterisk"

# MD050 - Strong style should be consistent
MD050:
  style: "asterisk"